// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Release_Candidate_Ervin_Hostetler.Models;

namespace Release_Candidate_Ervin_Hostetler.Migrations
{
    [DbContext(typeof(Release_Candidate_Ervin_HostetlerContext))]
    partial class Release_Candidate_Ervin_HostetlerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Release_Candidate_Ervin_Hostetler.Models.AmazonPurchase", b =>
                {
                    b.Property<int>("AmazonPurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("PurchasePrice");

                    b.Property<int>("Quantity");

                    b.Property<int>("ShippingCost");

                    b.Property<string>("URL");

                    b.HasKey("AmazonPurchaseId");

                    b.ToTable("AmazonPurchase");
                });

            modelBuilder.Entity("Release_Candidate_Ervin_Hostetler.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("TicketNumber");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Release_Candidate_Ervin_Hostetler.Models.Labor", b =>
                {
                    b.Property<int>("LaborId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("LaborCost");

                    b.Property<int>("Quantity");

                    b.HasKey("LaborId");

                    b.ToTable("Labor");
                });

            modelBuilder.Entity("Release_Candidate_Ervin_Hostetler.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("PurchasePrice");

                    b.Property<int>("Quantity");

                    b.Property<int>("ShippingCost");

                    b.Property<string>("URL");

                    b.HasKey("PurchaseId");

                    b.ToTable("Purchase");
                });
#pragma warning restore 612, 618
        }
    }
}
